os: Visual Studio 2015

platform:
    - x64
    - x86

cache:
    - sw -> win-ci.py

environment:
    matrix:
        - PY: 36


build_script:
    - ps: |
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
        }
    - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
    - C:/Python36-x64/python.exe win-ci.py install_deps
    - git clone --depth 1 "https://github.com/html5lib/html5lib-tests.git" test/html5lib-tests

test_script:
    - C:/Python36-x64/python.exe win-ci.py test
